### ISSUE TITLE
Ansible 2.10.0 and 1.0.0 before 2020-08-18

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.digitalocean#10]
##### SUMMARY

Related: https://github.com/ansible-collections/community.grafana/issues/111

> The 2020-08-18 date is of particular importance. This means that by that day, you MUST have released 1.0.0 for it to appear in Ansible 2.10. If you only have a 0.x.y release by then, we will not automatically include a newer version since according to semver, anything can happen and no stability guarantees are made. So please make sure that you released 1.0.0 by then.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

collection

##### ADDITIONAL INFORMATION

We will need to resolve https://github.com/ansible-collections/community.digitalocean/issues/1 first, then make sure this collection is stable, and then tag a 1.0.0 release.

**Comment by rockaut** [comment]
Leaving this here too:
1) The Bullhorn (the Ansible Contributor newsletter) https://us19.campaign-archive.com/home/?u=56d874e027110e35dea0e03c1&id=d6635f5420
2) Changes impacting Contributors ansible-collections/overview#45

**Comment by geerlingguy** [comment]
Closing in favor of #11 — still need to resolve #1 first, and I'm working on that now.
