### ISSUE TITLE
digital_ocean_droplet_info - 404

### ISSUE THREAD

**Issue by fey** [ansible-collections/community.digitalocean#117]
##### SUMMARY
https://docs.ansible.com/ansible/2.9/collections/community/digitalocean/digital_ocean_droplet_info.html
https://docs.ansible.com/ansible/latest/collections/community/digitalocean/digital_ocean_droplet_info.html

link to digital_ocean_droplet_info is broken or page do not exists

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
digital_ocean_droplet_info

**Comment by mamercad** [comment]
We rely on the upstream Ansible project to regenerate these docs (it's out of our control).
