### ISSUE TITLE
Mitigate sanity test ignores by fixing the actual problems

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.digitalocean#13]
##### SUMMARY

Currently the `sanity` tests for this module have a number of rules ignored (16 total) in https://github.com/ansible-collections/community.digitalocean/blob/main/tests/sanity/ignore-2.11.txt

It would be nice if we could get that down to zero—or just a couple.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Tests

##### ANSIBLE VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

**Comment by mamercad** [comment]
Agree, working on it.

**Comment by gundalow** [comment]
Cleaned up by #54

Now we only have `ignore-2.9.txt` https://github.com/ansible-collections/community.digitalocean/tree/main/tests/sanity
