### ISSUE TITLE
Get DigitalOcean credentials/integration so we can run integration tests

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.digitalocean#15]
##### SUMMARY

All the existing integration tests (and pretty much all functionality for these modules) requires a valid DigitalOcean subscription to be able to test with.

It would be great if we could figure out some way of getting a test/community account set up so we could build and tear down test infrastructure in DigitalOcean, though one major concern would be making sure all resources are _always_ torn down even when test runs fail or throw exceptions.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Integration tests

##### ADDITIONAL INFORMATION

(Created after @felixfontein noticed in #1 that the tests were never actually run in shippable in ansible/ansible, either.)

**Comment by gundalow** [comment]
If anyone at DigitalOcean wants to chat about how this could be implemented please comment here, or email me at my GitHub username @ redhat.com

**Comment by mamercad** [comment]
We have a secret defined for this!

**Comment by gundalow** [comment]
> We have a secret defined for this, it's named `DO_API_KEY`.

@mamercad how many requests can we put though this API key?
It would be good if we could do one CI run with coverage enabled so we can identify any gaps in integration tests.

**Comment by mamercad** [comment]
Presumably the same API limits as any other account (5000 requests/hr),
but, I'm just guessing. I've spoken to folks internally, and, there's a way
to raise the limit if we bump into it.

Here's a link to the docs:
https://developers.digitalocean.com/documentation/v2/#rate-limit

Sounds like the limits are returned in the response headers, which is
pretty cool.

Mark

**Comment by mamercad** [comment]
Thanks to @bmildren, we have a working API key now, going to close this issue.
