### ISSUE TITLE
Use network address when connecting to dynamic hosts

### ISSUE THREAD

**Issue by psommersguter** [ansible-collections/community.digitalocean#172]
##### SUMMARY
I am writing a playbook to automatically create droplets (if they don't exist) and configure them.
Therefore I would like to use the dynamic inventory plugin to discover and connect to the servers. 

Unfortunately, from what I can see, the inventory plugin only adds the host names of the droplets to the inventory which causes the connection to fail since my machine has no idea about hosts that were just created without manually adding configuration.
In a previous project I used the Hetzner Cloud Inventory Plugin which adds the hosts to the inventory in a way that makes Ansible uses the network address when establishing a connection.
This does not seem to be possible with the DigitalOcean Inventory Plugin. Or am I missing something?

My suggestion would be to make the DigitalOcean Inventory Plugin behave similar to the Hetzner Cloud Inventory Plugin to make my use case possible.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
DigitalOcean Inventory Plugin

##### ADDITIONAL INFORMATION
You can check out the relevant lines in the Hetzner Cloud Inventory Plugin here:
https://github.com/ansible-collections/hetzner.hcloud/blob/28eb3404f304dbb8c0421a2002844715ac6ffd43/plugins/inventory/hcloud.py#L35
https://github.com/ansible-collections/hetzner.hcloud/blob/28eb3404f304dbb8c0421a2002844715ac6ffd43/plugins/inventory/hcloud.py#L199

**Comment by mamercad** [comment]
I don't use the dynamic inventory plugin often, but, it seems to do the right thing with `ansible_host`:

```bash
❯ doctl compute droplet list -o json | jq -r '.[0] | .name, .networks.v4[0].ip_address'
delete1
137.184.202.215

❯ ansible-inventory -i digitalocean.yml --list | jq -r '._meta.hostvars.delete1.ansible_host'
137.184.202.215

❯ grep -v ^# digitalocean.yml
plugin: community.digitalocean.digitalocean
api_token: '{{ lookup("env", "DO_API_TOKEN") }}'
attributes:
  - id
  - name
  - memory
  - vcpus
  - disk
  - size
  - image
  - networks
  - volume_ids
  - tags
  - region
keyed_groups:
  - key: do_region.slug
    prefix: 'region'
    separator: '_'
  - key: do_tags | lower
    prefix: ''
    separator: ''
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public')
    | map(attribute='ip_address') | first
  class: do_size.description | lower
  distro: do_image.distribution | lower
```

**Comment by psommersguter** [comment]
Thanks for the quick reply!

I was actually about to write that I figured it out in the meantime.
You are totally correct, the "compose" (as defined in the examples) configuration does the trick:
```
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public')
    | map(attribute='ip_address') | first
```

Though IMHO it's not very intuitive that a user of the plugin must specify that via a rather complicated jinja expressions.
I think having a dedicated configuration option like the Hetzner Cloud plugin would be more convenient.

Anyway, if you don't decide to go forward with the idea I can understand it since technically the plugin covers my use case (if configured correctly) and the configuration is actually part of the official examples (though not that obvious).

**Comment by mamercad** [comment]
Since the functionality is present, going to close this issue for now.
