### ISSUE TITLE
Inventory plugin does not allow filtering with lookups

### ISSUE THREAD

**Issue by eproxus** [ansible-collections/community.digitalocean#214]
##### SUMMARY
When using the inventory plugin and filters, using a lookup will make the filter fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
DigitalOcean Inventory Plugin

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.1]
  config file = /Users/user/.ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.1 (main, Dec  6 2021, 22:25:40) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/Cellar/ansible/5.1.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection             Version
---------------------- -------
community.digitalocean 1.14.0
```

##### CONFIGURATION

```paste below
<NO OUTPUT>
```

##### OS / ENVIRONMENT

macOS 12.1

##### STEPS TO REPRODUCE

The command `pulumi stack output droplets` outputs the following when run:

```sh
$ pulumi stack output droplets
["app-01"]
```

The following filter does not work:

```yaml
plugin: community.digitalocean.digitalocean
filters:
  - 'do_name in lookup("pipe", "pulumi stack output droplets")'
```

If I use `'do_name in ["app-01"]'` it does work (but is not what I want since it is hardcoded).

I'm trying to make it so the inventory plugin only returns droplets which I have previously provisioned with Pulumi (by registering the droplet names in Pulumi and accessing them with the above command.

I would like to avoid using Digital Ocean tags since I already have the list of hosts I want to operate on in Pulumi. If there's a better way to do this, I'm open for suggestions.

##### EXPECTED RESULTS

I can filter using results from lookups.

##### ACTUAL RESULTS

Filters silently fail with `-vvv` messages like:
```
Host app-01 did not pass all filters
```

```paste below
$ ansible-inventory -vvv -i myinventory.digitalocean.yaml --graph
ansible-inventory [core 2.12.1]
  config file = /Users/user/.ansible.cfg
  configured module search path = ['/Users/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.1.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.10.1 (main, Dec  6 2021, 22:25:40) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
Using /Users/user/.ansible.cfg as config file
host_list declined parsing /Users/user/project/myinventory.digitalocean.yaml as it did not pass its verify_file() method
script declined parsing /Users/user/project/myinventory.digitalocean.yaml as it did not pass its verify_file() method
Sending request to https://api.digitalocean.com/v2/droplets?per_page=200
Host app-01 did not pass all filters
Host db-01 did not pass all filters
Host db-02 did not pass all filters
Host db-03 did not pass all filters
Parsed /Users/user/project/myinventory.digitalocean.yaml inventory source with auto plugin
@all:
  |--@ungrouped:
```

##### Notes

I think the problem lies in using `_compose` on the filter: https://github.com/ansible-collections/community.digitalocean/blob/main/plugins/inventory/digitalocean.py#L235

That function renders the filter template with the `disable_lookups=True` flag so lookups are just not parsed.

**Comment by mamercad** [comment]
Yeah, seems to be the `disable_lookups=True` (flipping it to `False` seems to do the trick).

**Comment by mamercad** [comment]
I've bugged [this](https://github.com/ansible/ansible/issues/76769) upstream.

**Comment by mamercad** [comment]
I've PR'd the change as well, not sure what'll happen of course. Since this isn't related to this project, I'm going to close the issue.

**Comment by mamercad** [comment]
Just a head's up, [this landed](https://github.com/ansible/ansible/pull/76770) in the `devel` branch.

**Comment by eproxus** [comment]
Quick work, thank you! ❤️

Will this inventory plug-in use `disable_lookups=False` now then?

**Comment by mamercad** [comment]
> Quick work, thank you! ❤️
> 
> Will this inventory plug-in use `disable_lookups=False` now then?

Heck no 😄 , I'm waiting for you to PR the change [here](https://github.com/ansible-collections/community.digitalocean/blob/ab6cb5608c46205695b6c6abcaeed9d5f6b81ecd/plugins/inventory/digitalocean.py#L235).

**Comment by mamercad** [comment]
And, I think based on the upstream PR, this won't land until Ansible 2.13.

**Comment by mamercad** [comment]
You can run `devel` locally if you like and test the change we're thinking will work as well.
