### ISSUE TITLE
Support for cloud-config

### ISSUE THREAD

**Issue by Lvl4Sword** [ansible-collections/community.digitalocean#222]
##### SUMMARY
Support for cloud-config ( example: https://www.digitalocean.com/community/tutorials/an-introduction-to-cloud-config-scripting )

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.digitalocean

##### ADDITIONAL INFORMATION
Ability to specify specific things within cloud-config while the droplet is being brought up.

```yaml
?
```

**Comment by mamercad** [comment]
This is already [supported](https://github.com/ansible-collections/community.digitalocean/blob/ab6cb5608c46205695b6c6abcaeed9d5f6b81ecd/plugins/modules/digital_ocean_droplet.py#L89).
