### ISSUE TITLE
AAAA record support for digital_ocean_domain

### ISSUE THREAD

**Issue by SRv6d** [ansible-collections/community.digitalocean#226]
##### SUMMARY
The digital_ocean_domain module does not support creating a `AAAA` record which is an essential feature.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
digital_ocean_domain

**Comment by mamercad** [comment]
Hrm, I'm not quad A functionality in [the API docs](https://docs.digitalocean.com/reference/api/api-reference/#operation/create_domain).

**Comment by mamercad** [comment]
Ah, I see the ability in the Cloud UI though; I'll dig.

**Comment by mamercad** [comment]
Created #230, just a head's up.
