### ISSUE TITLE
Documenting Spaces

### ISSUE THREAD

**Issue by Lvl4Sword** [ansible-collections/community.digitalocean#236]
##### SUMMARY
https://docs.ansible.com/ansible/latest/collections/community/digitalocean/index.html lacks anything to do with Spaces.
I was going to file an issue asking for Spaces support before seeing https://github.com/ansible-collections/community.digitalocean/pull/216

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

digital_ocean_spaces , digital_ocean_spaces_info

##### ANSIBLE VERSION

```paste below
Not applicable
```

**Comment by mamercad** [comment]
Yeah; to be honest, I'm not quite sure how docs.ansible.com works. The Spaces modules were added in 1.15.0 (and they're on the `README.md`) right now, but docs.ansible.com is references 1.14.0.

**Comment by mamercad** [comment]
There's nothing to do on this end to update docs.ansible.com (presumably there's a Redhat process involved), so, I'm going to close this issue.
