### ISSUE TITLE
Add project_name parameter support for kubernetes cluster

### ISSUE THREAD

**Issue by tornike** [ansible-collections/community.digitalocean#264]
##### SUMMARY

Everything is pretty simple, I think that project_name parameter is a must have for any resource that can be created inside the project, Kubernetes cluster in this case.

##### ISSUE TYPE
No project_name parameter in kubernetes module.

##### COMPONENT NAME

digital_ocean_kubernetes

**Comment by mamercad** [comment]
I don't see that as an option as far as the [API](https://docs.digitalocean.com/reference/api/api-reference/#tag/Kubernetes) goes, please reopen if I'm missing something.

**Comment by mamercad** [comment]
Oh, perhaps [this](https://docs.digitalocean.com/reference/api/api-reference/#operation/assign_project_resources) would work, let me investigate.

**Comment by mamercad** [comment]
Looks like it should, the URNs for Kubernetes clusters look like this `do:kubernetes:bd5f5959-5e1e-4205-a714-a914373942af`.

**Comment by raman-babich** [comment]
FYI, working on pr.
