### ISSUE TITLE
Add a testing quick start

### ISSUE THREAD

**Issue by coreywright** [ansible-collections/community.digitalocean#268]
##### SUMMARY

As a drive-by contributor, I don't care about the setup details of `ansible-test`, but instead just want to know how to minimally set up the repository to quickly cycle between development and testing.  Literally, I care so little that I just want someone to explicitly tell me what to do.

eg
```
$ # create directory structure as required by ansible-test: ansible_collections/community/digitalocean
$ mkdir -p ansible_collections/community
$ git clone ssh://git@github.com/ansible-collections/community.digitalocean ansible_collections/community/digitalocean
$ cd ansible_collections/community/digitalocean
$ ansible-test integration --list
$ ansible-test integration digital_ocean_droplet
```

Ctherwise a contributor is confronted with either:
* ```
    ERROR: The current working directory must be at or below:
    
     - an Ansible collection: {...}/ansible_collections/{namespace}/{collection}/
    
    Current working directory: /home/user/community.digitalocean
* Having to develop and test in two separate locations: develop in the local git repo and test where ever `ansible-galaxy` installs the collection from the local git repo.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
README.md, `Testing and Development` section

##### ANSIBLE VERSION
n/a

**Comment by mamercad** [comment]
@coreywright What do you think, is this more helpful than what's currently there?
