### ISSUE TITLE
CI doesn't run on main branch, only on PRs

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.digitalocean#29]
I think this list: https://github.com/ansible-collections/community.digitalocean/blob/main/.github/workflows/ansible-test.yml#L3 should also contain `push` as in https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml#L10.

While you're at it, you might also want to configure nightly runs (see https://github.com/ansible-collections/community.mysql/blob/main/.github/workflows/ansible-test-plugins.yml#L13-L14 for an example).

**Comment by felixfontein** [comment]
That would also ensure that the badges at the top of https://github.com/ansible-collections/community.digitalocean/blob/main/README.md aren't so grey :)

**Comment by gundalow** [comment]
@felixfontein Should we have nightlies added to https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml?

**Comment by felixfontein** [comment]
@gundalow that's probably a good idea.
