### ISSUE TITLE
Github codeowners functionality doesn't work for the repo

### ISSUE THREAD

**Issue by raman-babich** [ansible-collections/community.digitalocean#328]
##### SUMMARY

I have made the pr #327 and no one from the maintainers was assigned to it. It looks like the syntax of the [file](https://github.com/ansible-collections/community.digitalocean/blob/main/CODEOWNERS) is not correct. It seems to me that we need `*` at the beginning.

##### ISSUE TYPE
- Bug Report

**Comment by mamercad** [comment]
Strange that it says "the CODEOWNERS file is valid":
<img width="1090" alt="image" src="https://github.com/ansible-collections/community.digitalocean/assets/6192266/45e7e1c8-3403-4086-add5-285cc2f92038">

But, yes, looks like we need a leading `* ...`.
