### ISSUE TITLE
RFE: List current droplets in DO account

### ISSUE THREAD

**Issue by lincolnthree** [ansible-collections/community.digitalocean#34]
##### SUMMARY

First, thanks for this collection. Trying to get into it a bit :) It does not appear possible to retrieve a list of droplets. I'm wondering if I've missed something, or if this is a feature gap, or something that's in progress. It seems like a fairly basic operation that should be possible, which is why I doubt myself :)

DO API: https://developers.digitalocean.com/documentation/v2/#list-all-droplets

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

digital_ocean_droplet

##### ADDITIONAL INFORMATION

Essentially, getting a list of droplets would allow operations to be run on all current, or a subset by tag/etc, of droplets, without needing to keep an inventory of droplet IDs. 

Forgive me if this isn't a good idea - still getting used to Ansible :)

```yaml

```

N/A

**Comment by geerlingguy** [comment]
It seems like following the convention of all the other modules in this collection, it would be good to have a `digital_ocean_droplet_facts` module.

**Comment by lincolnthree** [comment]
@geerlingguy Or `digital_ocean_droplet_info` yeah.

**Comment by lincolnthree** [comment]
Here's a working example with URI, using the DO API, for anyone else who ends up here:

**required parameters:**
`oauth_token`: your D.O. API key token

**result:**
List of droplets, as JSON objects

```
- name: Gather information about all droplet sizes
  uri:
    url: https://api.digitalocean.com/v2/droplets?page=1&per_page=1000
    method: GET
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ oauth_token }}"
    return_content: yes
    status_code: [200]
  register: _response

- name: Print Response
  debug:
    msg: "{{ _response.json }}"

- name: Set facts based on the gathered information
  set_fact:
    droplets: "{{ _response.json | json_query('droplets') }}"

- name: Print Droplet List
  debug:
    msg: "{{ droplets }}"

```

**Comment by lincolnthree** [comment]
Could use this as a starting point: 

https://galaxy.ansible.com/hugonz/do_im_inventory
