### ISSUE TITLE
RFE: Managed database modules 

### ISSUE THREAD

**Issue by grzs** [ansible-collections/community.digitalocean#37]
##### SUMMARY
Module to create and manage managed database in DO

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
N/A

##### ADDITIONAL INFORMATION
This feature is available via the v2 API
https://developers.digitalocean.com/documentation/v2/#databases

**Comment by mamercad** [comment]
I'm working on this.

**Comment by mamercad** [comment]
Released in 1.3.0.
