### ISSUE TITLE
Digital Ocean Dynamic Inventory plugin

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/community.digitalocean#8]
##### SUMMARY
Deprecate the use of DO inventory script and introduce dynamic inventory plugin.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
plugins/inventory/digital_ocean.py

**Comment by sgpinkus** [comment]
Please don't depr the use of the inventory script.  It's much easier to use and debug than a plugin.

**Comment by mamercad** [comment]
I'm not sure it "hurts anything" to keep the script around, and I think https://github.com/ansible-collections/community.digitalocean/pull/41 satisfies the inventory plugin. Go ahead and re-open, or, create a new issue if you feel strongly about deprecating the script.
