### ISSUE TITLE
Database module setting self.version with incorrect attribs

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible-collections/community.digitalocean#94]
##### SUMMARY
In the `digital_ocean_database` module, it looks like when it is looking to see if a database exists, it is repeatedly overwriting `self.version` with a number of params. I'm assuming this was just a copy paste error and it should correctly set the appropriate attributes instead.

https://github.com/ansible-collections/community.digitalocean/blob/main/plugins/modules/digital_ocean_database.py#L197-L200
https://github.com/ansible-collections/community.digitalocean/blob/main/plugins/modules/digital_ocean_database.py#L222-L224

Is this intentional? Or should this be fixed?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`digital_ocean_database`

##### ANSIBLE VERSION

```paste below
ansible 2.9.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tyler/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.4 (default, Apr  6 2021, 00:00:00) [GCC 11.0.1 20210324 (Red Hat 11.0.1-0)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
NAME=Fedora
VERSION="34 (Workstation Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by mamercad** [comment]
Nice catch, looks like a copy/paste error as you mentioned.

**Comment by mamercad** [comment]
Thanks for all the help as of late @tylerauerbeck, if you're ever interested in chatting, we hang out in `#ansible-digitalocean` on Freenode (this'll likely change in the next few days, but, will likely be IRC still). This is the [bug](https://github.com/ansible-community/community-topics/issues/19) that tracks what's next.

**Comment by tylerauerbeck** [comment]
Absolutely! Happy to help out here. Will definitely look to swing by in the near future (and will keep an eye out on where everyone happens to land next).
